"""first

Revision ID: 577d1f4f42cf
Revises: 
Create Date: 2024-10-16 00:07:39.215763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577d1f4f42cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_data',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_data')
    # ### end Alembic commands ###
