"""db order by created

Revision ID: 82d0f565ba2b
Revises: 577d1f4f42cf
Create Date: 2024-10-16 00:21:55.495975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d0f565ba2b'
down_revision = '577d1f4f42cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_data', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
